CHROMIUM: Declare timed_freeze() inside #ifdef CONFIG_GENERIC_CLOCKEVENTS_BUILD
timed_freeze() is built if CONFIG_GENERIC_CLOCKEVENTS_BUILD is enabled,
but declared in the include file if CONFIG_SUSPEND is enabled.

This results in the following build error if CONFIG_SUSPEND is disabled
and CONFIG_GENERIC_CLOCKEVENTS_BUILD is enabled.

kernel/time/clockevents.c:335: error:
	redefinition of 'timed_freeze'
include/linux/suspend.h:292: error:
	previous definition of 'timed_freeze' was here

Declaring timed_freeze() inside #ifdef CONFIG_GENERIC_CLOCKEVENTS_BUILD
fixes the problem.

BUG=chrome-os-partner:51441
TEST=powerd_dbus_suspend

Change-Id: Id04b8fae09fd2796a4bfce20cd4d098a833eee83
Fixes: 90de2da206b8 ("CHROMIUM: clockevents: Add timed freeze")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/351502
Tested-by: Guenter Roeck <groeck@google.com>
Reviewed-by: Derek Basehore <dbasehore@chromium.org>