CHROMIUM: thermal: mtk driver depends on CPU_FREQ and must be built into kernel
The folowing build errors are seen on test builds trying to build the mediatek
thermal driver as module and with CPU_FREQ not enabled.

drivers/thermal/mtk_thermal.c: In function 'mtk_svs_hw_init':
drivers/thermal/mtk_thermal.c:1107:3: error:
	implicit declaration of function 'cpufreq_get_policy'
drivers/thermal/mtk_thermal.c:1136:3: error:
	implicit declaration of function 'cpufreq_update_policy'
drivers/thermal/mtk_thermal.c: At top level:
drivers/thermal/mtk_thermal.c:1485:1: error:
	 	redefinition of '__inittest'
drivers/thermal/mtk_thermal.c:1281:1: note:
	previous definition of '__inittest' was here
drivers/thermal/mtk_thermal.c:1485:1: error:
	redefinition of 'init_module'
drivers/thermal/mtk_thermal.c:1281:1: note:
	previous definition of 'init_module' was here

Commit 5be71f4c13d3 ("BACKPORT: FROMLIST: PM / AVS: thermal: MT8173: Introduce
support for SVS engine") introduces calls into the CPU frequency code, thus
adding a dependency of the Mediatek thermal driver on CPU_FREQ. It also adds
a late_initcall(), which in modular builds is mapped to module_init(). This
conflicts with the already existing module initialization.

BUG=chromium:616355
TEST=Try to build as module; try to build with CPU_FREQ disabled

Fixes: 5be71f4c13d3 ("BACKPORT: FROMLIST: PM / AVS: thermal: MT8173: Introduce support for SVS engine")
Change-Id: I7dd703e38c68306eb10b19ffbacb59885134acf2
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/348651
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>