CHROMIUM: FIXUP wireless42 use of debugfs_create_bool
The following commit introduced a build failure for gale:
     https://chromium-review.googlesource.com/#/c/330357/

commit 7ae890e4014b ("BACKPORT: debugfs: Pass bool pointer to debugfs_create_bool()")

Author: Daniel Kurtz <djkurtz@chromium.org>
Date:   Fri May 6 20:58:04 2016 +0800

One of two failures:
.../net/mac80211-4.2/debugfs.c:257:8:
error: passing argument 4 of 'debugfs_create_bool' from incompatible
pointer type [-Werror]
        &local->rx_stats_enabled);
        ^

BUG=none
TEST=emerge-gale gale-kernel-3_18
    (This is building from chromeos-3_18 branch)

Change-Id: I393ea924d398e5f46dd8ff7d68ffc33e9f1e4085
Signed-off-by: Grant Grundler <grundler@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/343550
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>